name: pipeline
on: 
  push: 
    branches: [ main ]        
env:
  test: test
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: print env
        run: |
          python3 
          import requests
          import re
          x = "Hi from python"
          print(x)
