name: pipeline
on: 
  push: 
    branches: [ main ]        
env:
  test: test
  TOKEN: ${{ secrets.TOKEN }}
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: print env
        run: |
          pip install requests
          pip install beautifulsoup4 
      - name: prin pwd
        run: pwd
      - name: ls
        run: ls -la
      - name: cd
        run: cd ../..
      - name: ls
        run: |
          pwd
          ls -la
      
          
