name: pipelinename
on:
  push:
    branches: [main]
env:
  test: test
  GITHUB_ACTOR: sercangithub
  TOKEN: ${{ secrets.TOKEN }}
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
jobs:
  mainpipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pwd
        run: |
          pwd
          ls -la
          cd test
          pwd
      - name: sdf
        run: |
          pwd

          
        
        

          
