name: pipeline
on: 
  push: 
    branches: [ main ]        
env:
  test: test
jobs:
  pipeline:
    if: github.event.head_commit.message == 'composer'
    runs-on: ubuntu-latest
    steps:
      - name: print env
        run: |
          echo "hi from main"
