name: pipeline
on: 
  push: 
    branches: [ main ]        
env:
  test: test
  TOKEN: acik
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install python module
        run: |
          pip install requests
          pip install beautifulsoup4 
      - name: print env
        run: echo $TOKEN
      - name: run python
        run: |
          python3 deneme.py > ip.txt
          ENV=$(cat ip.txt)
      - name:
        run: echo $ENV

          
