name: pipeline
on: 
  push: 
    branches: [ main ]        
env:
  test: test
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: print env
        if: github.event.pull_request.merged == true
        run: |
          echo "hi from main"
