name: pipeline
on: 
  push: 
    branches: [ main ]        
env:
  test: test
  TOKEN: acik
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
jobs:
  pipeline:
    if: github.event.head_commit.message == 'calis'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install python module
        run: |
          pip install requests
          pip install beautifulsoup4 
      - name: print env
        run: echo $TOKEN
      - name: run python
        run: |
          cd test
          python3 deneme.py > ip.txt
      - name: git push
        run:
          cd test
          ls -la
          
        
        

          
