name: pipeline
on: 
  push: 
    branches: [ main ]        
env:
  test: test
  GITHUB_ACTOR: sercangithub
  TOKEN: ${{ secrets.TOKEN }}
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
jobs:
  pipeline:
    if: github.event.head_commit.message == 'calis'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: instaAll python module
        run: |
          pip install requests
          pip install beautifulsoup4 
      - name: print env
        run: echo $TOKEN
      - name: run python
        run: |
          cd test
          python3 deneme.py > ip.txt
      - name: git push
        run: |
          cd test
          MYENV=$(cat ip.txt)
          git clone https://$GITHUB_ACTOR:$GIT_TOKEN@github.com/sercangithub/pipelinetest
          cd pipelinetest
          git config --global user.mail "sercanbeyazoglu@yahoo.com"
          git config --global user.name "sercangithub"
          sed -i 's|ds|'$MYENV'|g' README.md
          git add -A
          git commit -m"test"
          git push
          
        
        

          
