name: pipeline
on:
  pull:
    branches: [ main ]
      type: [ closed ]        
env:
  test: test
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: print env
        if: 
        echo: github.event.pull_request == true
        run: |
          echo $GITHUB_REF_NAME
          echo hi
