name: pipeline
on:
  push:
    branches: [ development ]
env:
  test: test
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: print env
        if: github.event.pull_request == true
        run: |
          echo $GITHUB_REF_NAME
