name: pipeline
on:
  pull_request:
    branches: [ main ]
    types: [ closed ]
env:
  test: test
  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: print env
        if: github.event.pull_request.merged == true
        run: |
          git clone https://$GITHUB_TOKEN:@github.com/sercangithub/pipelinetest.git -b development
          cd pipelinetest/
          git config --global user.email "sercanbeyazoglu@yahoo.com"
          git config --global user.name "sercangithub"
          echo "hi" >> test.txt
          git add -A
          git commit -m "composer"
          git push origin main
